# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `openssl-signature_algorithm` gem.
# Please instead update this file by running `bin/tapioca gem openssl-signature_algorithm`.


# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca#manually-requiring-parts-of-a-gem
