sources:
  bundler: true

cache_path: .licenses

# All these licenses are compatible with AGPLv3
allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - ruby
  - lgpl-2.1
  - lgpl-3.0
  - mpl-2.0
  - public_domain
  - unlicense
  - cc0-1.0
  - wtfpl
  - 0bsd
  - gpl-2.0
  - gpl-3.0
  - agpl-3.0

# Mark "other" licenses as reviewed (mostly Ruby stdlib)
reviewed:
  bundler:
    - other