sources:
  bundler: true

allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - ruby
  - lgpl-2.1
  - lgpl-3.0
  - mpl-2.0
  - public_domain
  - unlicense
  - cc0-1.0
  - wtfpl
  - 0bsd

# These licenses are generally compatible with AGPLv3
# but may require attribution or other requirements
reviewed:
  bundler:
    - gpl-2.0
    - gpl-3.0
    - agpl-3.0

cache_path: .licenses