# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Load custom cops
require:
  - ./lib/rubocop/cop/custom/ternary_line_breaks
  - ./lib/rubocop/cop/custom/one_line_methods

# Load plugins
plugins:
  - rubocop-sorbet

# Enable custom cops
Custom/TernaryLineBreaks:
  Enabled: true

Custom/OneLineMethods:
  Enabled: true

# Enable Sorbet cops
Sorbet/BlockMethodDefinition:
  Enabled: true
  
Sorbet/Refinement:
  Enabled: true

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
