plugins:
  - standard-rails
ignore:
  - 'db/seeds/**/*':
    - Style/GlobalVars
  - 'db/schema.rb':
    - Rails/CreateTableWithTimestamps
  - 'app/services/pdf_cache_service.rb':
    # CacheResult intentionally enforces keyword-only initialization.
    - Style/RedundantStructKeywordInit
