# typed: true
# frozen_string_literal: true

# Fix SolidQueue loading issue - ensure adapter exists before ActiveJob needs it
require "active_job"
require "active_job/queue_adapters"

# Load SolidQueue and its adapter
require "solid_queue"
require "active_job/queue_adapters/solid_queue_adapter"

# Load ActiveModel first to fix SolidQueue loading issue
require "active_model"
require "active_model/callbacks"
require "abstract_controller"
require "abstract_controller/base"
require "action_controller/railtie"
require "action_controller"
require "action_controller/metal"
require "action_controller/base"
require "action_controller/metal/helpers"
require "action_controller/metal/redirecting"
require "action_controller/metal/rendering"
require "action_controller/metal/params_wrapper"
require "action_controller/metal/cookies"
require "action_controller/metal/flash"
require "action_controller/metal/request_forgery_protection"
require "action_controller/metal/strong_parameters"
require "action_dispatch/http/response"
require "action_dispatch/http/request"
require "action_dispatch/http/headers"
require "action_dispatch/middleware/flash"
require "action_dispatch/middleware/cookies"
require "action_view/railtie"
require "action_view/base"
require "action_view/helpers"
require "active_model/railtie"
require "active_model/errors"
require "active_model/error"
require "active_record/railtie"
require "active_record/base"
require "active_record/core"
require "active_record/persistence"
require "active_record/associations"
require "active_record/scoping/named"
require "active_record/validations"
require "active_record/callbacks"
require "active_record/enum"
require "active_record/reflection"
require "active_record/attribute_methods"
require "active_record/model_schema"
require "active_record/inheritance"
require "active_storage/engine"
require "active_storage/attached/model"
require "active_storage/attached/one"
require "active_storage/attached/many"
require "active_job"
require "solid_queue"
require "active_job/queue_adapters"
require "active_job/queue_adapters/solid_queue_adapter"
# require "active_job/railtie"
require "active_support/core_ext/integer/time"
# Load ActiveSupport nested classes
require "active_support/time_with_zone"
require "active_support/duration"
require "active_support/multibyte/chars"
require "active_support/hash_with_indifferent_access"
require "active_support/core_ext/string/output_safety"
require "active_support/concern"
require "active_support/logger"
require "active_support/tagged_logging"
# Load ActiveRecord nested classes
require "active_record/associations/collection_proxy"
require "active_record/relation/batches/batch_enumerator"
require "active_record/type"
# Load ActiveStorage nested classes
require "active_storage/service/s3_service"
require "aws-sdk-s3"
require "capybara/cuprite"
require "capybara/rspec"
require "chobble-forms"
require "csv"
require "database_cleaner/active_record"
require "dotenv/load"
require "en14960"
require "en14960/api"
require "en14960/constants"
require "en14960/calculators/slide_calculator"
require "en14960/calculators/anchor_calculator"
require "en14960/calculators/user_capacity_calculator"
require "factory_bot_rails"
require "json"
require "net/http"
require "open3"
require "pdf/inspector"
require "prawn"
require "prawn/document"
require "prawn/errors"
require "prawn/table"
require "rails"
require "rails/all"
require "rails/test_help"
require "rails/test_unit/railtie"
require "rqrcode"
require "rspec_junit_formatter"
require "rubocop"
require "rubocop/cop/base"
require "rubocop/rspec/support"
# Load Google Protobuf classes
require "google/protobuf"
# Load Prism nested classes
require "prism"
require "sassc"
require "sentry-rails"
require "sentry-ruby"
require "sentry/configuration"
require "simplecov"
require "simplecov-cobertura"
require "timeout"
require "uri"
require "vips"
