name: 'Git Setup for Automation'
description: 'Configure git for automated commits and PRs'

runs:
  using: "composite"
  steps:
    - name: Configure git user
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"