name: 'Setup Test Environment'
description: 'Sets up the common test environment for CI workflows'

runs:
  using: "composite"
  steps:
    - name: Install packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: google-chrome-stable curl libjemalloc2 sqlite3 libvips42 imagemagick-6.q16
        version: 1.1
        execute_install_scripts: true

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Disable man-db update
      shell: bash
      run: sudo rm -f /var/lib/man-db/auto-update

    - name: Cache ImageMagick
      uses: actions/cache@v4
      id: imagemagick-cache
      with:
        path: |
          /usr/bin/mogrify
          /usr/bin/identify
          /usr/bin/convert
        key: ${{ runner.os }}-imagemagick-binaries-v1
        
    - name: Install ImageMagick if not cached
      shell: bash
      if: steps.imagemagick-cache.outputs.cache-hit != 'true'
      run: |
        echo "ImageMagick not cached, installing..."
        # sudo apt-get update -qq
        sudo apt-get install -y -qq imagemagick
        
    - name: Verify ImageMagick installation
      shell: bash
      run: |
        echo "Verifying ImageMagick installation:"
        which mogrify || (echo "ERROR: mogrify not found" && exit 1)
        which identify || (echo "ERROR: identify not found" && exit 1)
        which convert || (echo "ERROR: convert not found" && exit 1)
