name: 'Setup Test Environment'
description: 'Sets up the common test environment for CI workflows'

runs:
  using: "composite"
  steps:
    - name: Install packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: google-chrome-stable curl libjemalloc2 sqlite3 libvips42
        version: 1.3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
        
