# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PublicFieldFiltering`.
# Please instead update this file by running `bin/tapioca dsl PublicFieldFiltering`.


module PublicFieldFiltering
  mixes_in_class_methods ::ColumnNameSyms::ClassMethods
end
