---
usage: opensource
integration:
  name: rspec
requires:
- ./config/environment
environment_variables:
  RAILS_ENV: test
matcher:
  subjects:
  - Credential
  - InspectorCompany
  - TextReplacement
