# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  s3_backup:
    class: S3BackupJob
    queue: default
    schedule: at 2am every day
    description: "Daily backup to S3"

test:
  s3_backup:
    class: S3BackupJob
    queue: default
    schedule: every 5 minutes
    description: "Test backup to S3 (runs every 5 minutes for testing)"

production:
  s3_backup:
    class: S3BackupJob
    queue: default
    schedule: at 2am every day
    description: "Daily backup to S3"
  
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
