form_fields:
  - legend_i18n_key: exit_requirements
    fields:
      - partial: number_pass_fail_comment
        field: exit_number
        attributes:
          min: 1
      - partial: pass_fail_comment
        field: exit_sign_always_visible_pass