form_fields:
  - legend_i18n_key: materials_assessment
    fields:
      - partial: number_pass_fail_na_comment
        field: ropes
        attributes:
          min: 0
      - partial: pass_fail_na_comment
        field: retention_netting_pass
      - partial: pass_fail_na_comment
        field: zips_pass
      - partial: pass_fail_na_comment
        field: windows_pass
      - partial: pass_fail_na_comment
        field: artwork_pass
      - partial: pass_fail_comment
        field: thread_pass
      - partial: pass_fail_comment
        field: fabric_strength_pass
      - partial: pass_fail_comment
        field: fire_retardant_pass