---
form_fields:
  - legend_i18n_key: markings
    fields:
      - partial: :pass_fail_comment
        field: :age_marking
      - partial: :pass_fail_comment
        field: :height_marking
  - legend_i18n_key: safety_checks
    fields:
      - partial: :pass_fail_comment
        field: :sight_line
      - partial: :pass_fail_comment
        field: :access
      - partial: :pass_fail_comment
        field: :suitable_matting
      - partial: :pass_fail_comment
        field: :traffic_flow
      - partial: :pass_fail_comment
        field: :air_juggler
      - partial: :pass_fail_comment
        field: :balls
      - partial: :pass_fail_comment
        field: :ball_pool_gaps
      - partial: :pass_fail_comment
        field: :fitted_sheet
  - legend_i18n_key: measurements
    fields:
      - partial: :number_pass_fail_comment
        field: :ball_pool_depth
        attributes:
          step: 1
          min: 0
      - partial: :number_pass_fail_comment
        field: :ball_pool_entry_height
        attributes:
          step: 1
          min: 0
      - partial: :number_pass_fail_comment
        field: :slide_gradient
        attributes:
          step: 1
          min: 0
      - partial: :number_pass_fail_comment
        field: :slide_platform_height
        attributes:
          step: 0.01
          min: 0
