---
form_fields:
  - legend_i18n_key: credentials
    fields:
      - partial: text_field
        field: :email
        attributes:
          type: email_field
          required: true
      - partial: text_field
        field: :password
        attributes:
          type: password_field
          required: true
      - partial: checkbox
        field: :remember_me
