---
form_fields:
  - legend_i18n_key: fabric_construction
    fields:
      - partial: pass_fail_comment
        field: seam_integrity
      - partial: pass_fail_comment
        field: stitch_length
      - partial: pass_fail_comment
        field: air_loss
      - partial: pass_fail_comment
        field: straight_walls
      - partial: pass_fail_comment
        field: sharp_edges
  - legend_i18n_key: structural_safety
    fields:
      - partial: pass_fail_comment
        field: unit_stable
      - partial: pass_fail_comment
        field: evacuation_time
      - partial: number_pass_fail_comment
        field: step_ramp_size
        attributes:
          step: 1
          min: 0
      - partial: number_pass_fail_comment
        field: platform_height
        attributes:
          step: 1
          min: 10
      - partial: number_pass_fail_comment
        field: critical_fall_off_height
        attributes:
          step: 1
          min: 10
      - partial: number_pass_fail_comment
        field: unit_pressure
        attributes:
          step: 0.01
          min: 0
  - legend_i18n_key: trough_assessment
    fields:
      - partial: integer_comment
        field: trough_depth
        attributes:
          min: 0
          add_not_applicable: true
      - partial: integer_comment
        field: trough_adjacent_panel_width
        attributes:
          min: 0
      - partial: pass_fail_comment
        field: trough
  - legend_i18n_key: safety_compliance
    fields:
      - partial: pass_fail_comment
        field: entrapment
      - partial: pass_fail_comment
        field: markings
      - partial: pass_fail_comment
        field: grounding
