form_fields:
  - legend_i18n_key: height_measurements
    fields:
      - partial: decimal_comment
        field: containing_wall_height
  - legend_i18n_key: play_area
    fields:
      - partial: decimal_comment
        field: play_area_length
        attributes:
          min: 0
      - partial: decimal_comment
        field: play_area_width
        attributes:
          min: 0
      - partial: decimal_comment
        field: negative_adjustment
        attributes:
          min: 0
  - legend_i18n_key: user_capacity
    fields:
      - partial: number
        field: users_at_1000mm
        attributes:
          min: 0
          step: 1
      - partial: number
        field: users_at_1200mm
        attributes:
          min: 0
          step: 1
      - partial: number
        field: users_at_1500mm
        attributes:
          min: 0
          step: 1
      - partial: number
        field: users_at_1800mm
        attributes:
          min: 0
          step: 1
      - partial: decimal_comment
        field: tallest_user_height
      - partial: number
        field: user_count_at_maximum_user_height
        attributes:
          min: 0
          step: 1