# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in chobble_app.gemspec
gemspec

group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.4"
  gem "standard", "~> 1.35"
  gem "sqlite3", "~> 1.4"
end