name: "Test: Ruby"

on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-suite:
          - controllers
          - features  
          - models
          - requests
          - services
          - helpers
          - lib
          - seeds
          - views

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Create .env file
        run: |
          echo "BASE_URL=localhost:3000" > .env
          echo "APP_NAME=Play-Test CI" >> .env

      - name: Prepare database
        env:
          RAILS_ENV: test
          CACHE_HIT: ${{ steps.db-cache.outputs.cache-hit }}
        run: |
          bundle exec rails db:migrate
          bundle exec rails parallel:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec parallel_rspec spec/${{ matrix.test-suite }}

