name: "Test: Ruby"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-suite:
          - controllers
          - features  
          - models
          - requests
          - services
          - helpers
          - lib
          - seeds
          - views

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: google-chrome-stable curl libjemalloc2 sqlite3 libvips42 imagemagick-6.q16
          version: 1.1
          execute_install_scripts: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Debug ImageMagick
        run: |
          echo "PATH: $PATH"
          echo "Looking for ImageMagick executables:"
          which identify || echo "identify not found in PATH"
          which mogrify || echo "mogrify not found in PATH"
          which convert || echo "convert not found in PATH"
          echo "Searching filesystem for ImageMagick:"
          find /usr -name "mogrify" 2>/dev/null || echo "mogrify not found in /usr"
          echo "Installed packages:"
          dpkg -l | grep -i imagemagick || echo "ImageMagick package not listed"

      - name: Prepare database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:migrate
          bundle exec rails parallel:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec parallel_rspec spec/${{ matrix.test-suite }}

