name: Coverage Report

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2am
  workflow_dispatch:  # Manual trigger

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run all tests with coverage
        env:
          RAILS_ENV: test
          SIMPLECOV_COBERTURA: true
          RSPEC_JUNIT_FORMATTER: true
          RSPEC_JUNIT_OUTPUT: junit.xml
        run: |
          bundle exec rails db:migrate
          bundle exec rails parallel:prepare
          bundle exec rake coverage:parallel

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run all tests with coverage (normal format)
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake coverage:parallel
  
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.COVERAGE_NEOCITIES_API_KEY }}
          cleanup: true
          neocities_supporter: true
          preview_before_deploy: false
          dist_dir: coverage
