name: Docker Build

on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push images to registries'
        required: false
        type: boolean
        default: false
      version:
        description: 'Version tag to use (without v prefix)'
        required: false
        type: string
        default: 'test'
    secrets:
      DOCKERHUB_TOKEN:
        required: false
      FORGEJO_TOKEN:
        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        if: inputs.push
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to Forgejo Registry
        if: inputs.push
        uses: docker/login-action@v3
        with:
          registry: git.chobble.com
          username: stefan
          password: ${{ secrets.FORGEJO_TOKEN }}
      
      - name: Login to GitHub Container Registry
        if: inputs.push
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Prepare Docker tags
        id: tags
        run: |
          if [ "${{ inputs.push }}" = "true" ]; then
            echo "tags<<EOF" >> $GITHUB_OUTPUT
            echo "${{ vars.DOCKER_USERNAME }}/play-test:latest" >> $GITHUB_OUTPUT
            echo "${{ vars.DOCKER_USERNAME }}/play-test:v${{ inputs.version }}" >> $GITHUB_OUTPUT
            echo "git.chobble.com/chobble/play-test:latest" >> $GITHUB_OUTPUT
            echo "git.chobble.com/chobble/play-test:v${{ inputs.version }}" >> $GITHUB_OUTPUT
            echo "ghcr.io/${{ github.repository }}:latest" >> $GITHUB_OUTPUT
            echo "ghcr.io/${{ github.repository }}:v${{ inputs.version }}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "tags=play-test:${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Prepare cache config
        id: cache
        run: |
          if [ "${{ inputs.push }}" = "true" ]; then
            echo "to<<EOF" >> $GITHUB_OUTPUT
            echo "type=gha,mode=max" >> $GITHUB_OUTPUT
            echo "type=registry,ref=${{ vars.DOCKER_USERNAME }}/play-test:buildcache,mode=max" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "to=type=gha,mode=max" >> $GITHUB_OUTPUT
          fi
      
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.push }}
          load: ${{ !inputs.push }}
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: |
            type=gha
            type=registry,ref=${{ vars.DOCKER_USERNAME }}/play-test:buildcache
          cache-to: ${{ steps.cache.outputs.to }}
      
      - name: Test Docker image
        if: '!inputs.push'
        run: |
          docker run --rm play-test:${{ inputs.version }} bundle exec rails --version
          docker run --rm play-test:${{ inputs.version }} ruby --version