name: "Deploy: Docker Image"

on:
  workflow_run:
    workflows: ["Test: Ruby"]
    branches: [main]
    types: [completed]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    # Only run if the test workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Forgejo Registry
        uses: docker/login-action@v3
        with:
          registry: git.chobble.com
          username: stefan
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/play-test:latest
            git.chobble.com/chobble/play-test:latest
            ghcr.io/${{ github.repository }}:latest
