name: "Lint: Standard Ruby"

on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
    - name: Run Standard Ruby linter
      uses: standardrb/standard-ruby-action@v1
