name: "Test: Ruby"

on:
  push:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-suite:
          - controllers
          - features  
          - models
          - requests
          - services
          - helpers
          - lib
          - seeds
          - views

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Prepare database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:migrate
          bundle exec rails parallel:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec parallel_rspec spec/${{ matrix.test-suite }}

